title: Principles of Backend Engineering
author: Joe Antonakakis and Ilan Filonenko
description: Course site for CS 1998 - Principles of Backend Engineering
baseurl: ""
url: 'https://github.com/Cornell-PoBE'
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Required for appropriate theme
theme: jekyll-whiteglass

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:

# Plugins
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
